-- [ANTICODE] Required Database Schema

-- 1. Channel Members Table (For Invites & Hidden Channels)
create table if not exists public.anticode_channel_members (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  channel_id text not null,
  username text not null,
  invited_by text,
  role text default 'member',
  status text default 'joined', -- [NEW] Added for invitation system
  unique(channel_id, username)
);

-- 2. Channel Blocks Table (For Kick & Ban)
create table if not exists public.anticode_channel_blocks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  channel_id text not null,
  blocked_username text not null,
  blocked_by text not null,
  unique(channel_id, blocked_username)
);

-- 3. Row Level Security (RLS) Policies for Anon Access
-- Enable RLS
alter table public.anticode_channel_members enable row level security;
alter table public.anticode_channel_blocks enable row level security;

-- Policies for Members
drop policy if exists "Enable all for anon on members" on public.anticode_channel_members;
create policy "Enable all for anon on members" on public.anticode_channel_members for all using (true) with check (true);

-- Policies for Blocks
drop policy if exists "Enable all for anon on blocks" on public.anticode_channel_blocks;
create policy "Enable all for anon on blocks" on public.anticode_channel_blocks for all using (true) with check (true);

-- 4. Enable Realtime
-- Run these commands to ensure clients receive events
alter publication supabase_realtime add table anticode_channel_members;
alter publication supabase_realtime add table anticode_channel_blocks;
alter publication supabase_realtime add table anticode_messages;
alter publication supabase_realtime add table anticode_friends;
