-- [ANTICODE] Required Database Schema

-- 1. Channel Members Table (For Invites & Hidden Channels)
create table if not exists public.anticode_channel_members (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  channel_id text not null,
  username text not null,
  invited_by text,
  role text default 'member',
  unique(channel_id, username)
);

-- 2. Channel Blocks Table (For Kick & Ban)
create table if not exists public.anticode_channel_blocks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  channel_id text not null,
  blocked_username text not null,
  blocked_by text not null,
  unique(channel_id, blocked_username)
);

-- 3. Enable Realtime (Critical for immediate updates)
-- Run these commands to ensure clients receive "INSERT" events
alter publication supabase_realtime add table anticode_channel_members;
alter publication supabase_realtime add table anticode_channel_blocks;
alter publication supabase_realtime add table anticode_messages;
