-- [ANTICODE] Add Shared Translation Cache Table
create table if not exists public.translations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  source_hash text not null, -- Index: MD5(original_text + ":" + target_lang)
  original_text text not null,
  target_lang text not null,
  translated_text text not null,
  usage_count int default 1
);

-- Index for fast lookup by hash
create unique index if not exists idx_translations_source_hash on public.translations(source_hash);

-- RLS Policies
alter table public.translations enable row level security;

-- Enable all for anon for now (read/write cache)
drop policy if exists "Enable all for anon on translations" on public.translations;
create policy "Enable all for anon on translations" on public.translations for all using (true) with check (true);
