-- [ANTICODE] Account Deletion & 90-Day Purge Logic
-- This script ensures compliance with privacy regulations and user requests.

-- 1. Table to track deletion requests
create table if not exists public.anticode_deletion_requests (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    username text not null,
    email text,
    status text default 'pending', -- 'pending', 'completed'
    execution_date timestamp with time zone default (now() + interval '90 days') -- Scheduled deletion date
);

-- 2. Function to perform the actual cleanup
-- This function deletes all user data across different tables.
create or replace function public.anticode_purge_deleted_users()
returns void as $$
declare
    target_user text;
begin
    -- Find users who reached their execution date
    for target_user in 
        select username from public.anticode_deletion_requests 
        where status = 'pending' and execution_date <= now()
    loop
        -- Delete from various tables (Adjust table names as necessary)
        delete from public.anticode_messages where username = target_user;
        delete from public.anticode_channel_members where username = target_user;
        delete from public.anticode_friends where username = target_user or friend_username = target_user;
        
        -- Update the request status
        update public.anticode_deletion_requests 
        set status = 'completed' 
        where username = target_user;
        
        raise notice 'Permanently purged data for user: %', target_user;
    end loop;
end;
$$ language plpgsql;

-- 3. Note on Automation
-- Since Supabase Free doesn't include pg_cron by default, 
-- you can run "select public.anticode_purge_deleted_users();" 
-- manually in the SQL Editor once a month, or trigger it via a GitHub Action/Edge Function.
