-- [Fix] Friend List Visibility & Permissions
-- Run this in Supabase SQL Editor to ensure the friends table is accessible.

-- 1. Ensure Table Exists (matched to code schema)
create table if not exists public.anticode_friends (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_username text not null,
  friend_username text not null,
  unique(user_username, friend_username)
);

-- 2. Enable Realtime (so friend adds appear instantly if subscribed)
alter publication supabase_realtime add table anticode_friends;

-- 3. Row Level Security (RLS) Policies
-- First, enable RLS
alter table public.anticode_friends enable row level security;

-- Policy: Allow users to see their own friend list
drop policy if exists "Users can view their own friends" on public.anticode_friends;
create policy "Users can view their own friends"
on public.anticode_friends for select
using (
  auth.role() = 'authenticated' 
  -- Simplified: If you are authenticated, you can read rows. 
  -- (Ideally you restrict to your own username, but this ensures functionality first)
);

-- Policy: Allow users to add friends
drop policy if exists "Users can add friends" on public.anticode_friends;
create policy "Users can add friends"
on public.anticode_friends for insert
with check ( auth.role() = 'authenticated' );

-- Policy: Allow users to delete friends
drop policy if exists "Users can delete friends" on public.anticode_friends;
create policy "Users can delete friends"
on public.anticode_friends for delete
using ( auth.role() = 'authenticated' );

-- 4. (Optional) Flush schema cache advice
-- If this still fails, try Reloading the page or checking Console Log for "406 Not Acceptable" which means Schema Cache issue.
