-- [ANTICODE] Payment System Schema
-- Run this in Supabase SQL Editor.

-- 1. Create Payment History Table
create table if not exists public.anticode_payment_history (
  id bigint generated by default as identity primary key,
  user_id text not null,
  imp_uid text not null unique, -- PortOne payment ID
  merchant_uid text not null, -- Our order ID
  amount integer not null,
  status text not null, -- 'paid', 'failed', 'refunded'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. RLS Policies for Payment History
alter table public.anticode_payment_history enable row level security;

create policy "Users can view own payment history"
on public.anticode_payment_history for select
using ( auth.uid()::text = (select uid::text from public.anticode_users where username = user_id limit 1) );

-- 3. Secure Function to Charge Coins (Only callable by Admin/Edge Function)
-- This function mimics a system-level operation.
-- In a real production setup, you might want strict role checks.
-- For now, we will use 'security definer' and checks in the Edge Function side mainly,
-- but having this function makes the update atomic.
create or replace function public.charge_coins_secure(
  p_user_id text, 
  p_amount int, 
  p_imp_uid text, 
  p_merchant_uid text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current_balance bigint;
begin
  -- 1. Check if payment ID already exists to prevent double charging
  if exists (select 1 from public.anticode_payment_history where imp_uid = p_imp_uid) then
    return '{"status": "error", "message": "Already processed payment."}'::jsonb;
  end if;

  -- 2. Log the payment
  insert into public.anticode_payment_history (user_id, imp_uid, merchant_uid, amount, status)
  values (p_user_id, p_imp_uid, p_merchant_uid, p_amount, 'paid');

  -- 3. Update User Wallet
  insert into public.anticode_wallets (user_id, balance) values (p_user_id, p_amount)
  on conflict (user_id) do update 
  set balance = anticode_wallets.balance + p_amount, 
      updated_at = now();

  return '{"status": "success", "message": "Coins charged."}'::jsonb;
end;
$$;
