-- [ANTICODE] Emoticon Open Market Schema (Fixed)
-- Run this in Supabase SQL Editor

-- 1. Wallets (Coin Balance)
create table if not exists public.anticode_wallets (
  user_id text primary key, -- References anticode_users.username
  balance bigint not null default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint fk_user foreign key (user_id) references public.anticode_users(username) on delete cascade
);

-- 2. Products (Emoticon Packs)
create table if not exists public.anticode_products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  price bigint not null default 0,
  type text not null default 'emoticon_pack', 
  content_data jsonb not null default '{}'::jsonb, 
  owner_id text,
  is_public boolean default true
);

-- 3. Purchases (Ownership)
create table if not exists public.anticode_purchases (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id text not null,
  product_id bigint not null references public.anticode_products(id),
  price_paid bigint not null,
  unique(user_id, product_id)
);

-- 4. RLS Policies
alter table public.anticode_wallets enable row level security;
alter table public.anticode_products enable row level security;
alter table public.anticode_purchases enable row level security;

-- Wallets: Users can view their own balance
-- FIX: Changed 'id' to 'uid' based on error log
drop policy if exists "Users can view own wallet" on public.anticode_wallets;
create policy "Users can view own wallet" on public.anticode_wallets for select
using ( user_id = (select username from anticode_users where uid::text = auth.uid()::text) );

-- Products: Everyone can view public products
drop policy if exists "Everyone can view public products" on public.anticode_products;
create policy "Everyone can view public products" on public.anticode_products for select
using ( is_public = true );

-- Purchases: Users can view their own purchases
-- FIX: Changed 'id' to 'uid'
drop policy if exists "Users can view own purchases" on public.anticode_purchases;
create policy "Users can view own purchases" on public.anticode_purchases for select
using ( user_id = (select username from anticode_users where uid::text = auth.uid()::text) );

-- 5. Realtime
alter publication supabase_realtime add table anticode_wallets;
alter publication supabase_realtime add table anticode_purchases;
alter publication supabase_realtime add table anticode_products;

-- 6. Secure Purchase Function (RPC)
-- FIX: Added 'set search_path' and fixed 'uid' reference
create or replace function public.purchase_product(p_product_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id text;
  v_price bigint;
  v_balance bigint;
begin
  -- Get current user's username via auth.uid() linkage
  select username into v_user_id from public.anticode_users where uid::text = auth.uid()::text;
  
  if v_user_id is null then
    return '{"status": "error", "message": "로그인이 필요합니다."}'::jsonb;
  end if;

  -- Get product price
  select price into v_price from public.anticode_products where id = p_product_id;
  if v_price is null then
    return '{"status": "error", "message": "상품을 찾을 수 없습니다."}'::jsonb;
  end if;

  -- Check if already owned
  if exists (select 1 from public.anticode_purchases where user_id = v_user_id and product_id = p_product_id) then
    return '{"status": "error", "message": "이미 보유한 상품입니다."}'::jsonb;
  end if;

  -- Ensure wallet exists
  insert into public.anticode_wallets (user_id, balance) values (v_user_id, 0)
  on conflict (user_id) do nothing;
  
  select balance into v_balance from public.anticode_wallets where user_id = v_user_id;
  
  if v_balance < v_price then
    return '{"status": "error", "message": "코인이 부족합니다."}'::jsonb;
  end if;

  -- Execute Transaction
  update public.anticode_wallets set balance = balance - v_price, updated_at = now() 
  where user_id = v_user_id;

  insert into public.anticode_purchases (user_id, product_id, price_paid)
  values (v_user_id, p_product_id, v_price);

  return '{"status": "success", "message": "구매가 완료되었습니다.", "balance": ' || (v_balance - v_price) || '}'::jsonb;
end;
$$;
